# Create a CloudWatch log group for lambda function logs, with a retention period of 7 days. This log group will store the logs generated by the Lambda functions used in the notifications system.
resource "aws_cloudwatch_log_group" "lambda_log_group" {
  # checkov:skip=CKV_AWS_338: Portfolio project optimized for cost insulation. Retaining logs for 1 year exceeds free tier limits.
  # checkov:skip=CKV_AWS_158: Portfolio porject- AWS default encryption is sufficient for a portfolio project, so using the default AWS-managed encryption to avoid additional costs from a custom KMS key.
  name              = "/aws/lambda/${var.environment}-notifications-lambda"
  retention_in_days = 7 # the logs will be saved in CloudWatch for 7 days, after which they will be automatically deleted. 
  #Adjust this value based on your log retention requirements and compliance policies.
  tags = {
    Name        = "${var.environment}-notifications-lambda-log-group"
    Environment = var.environment
    Module      = "notifications"
  }
}
