# Create a CloudWatch log group for lambda function logs, with a retention period of 30 days. This log group will store the logs generated by the Lambda functions used in the notifications system.
resource "aws_cloudwatch_log_group" "lambda_log_group" {
  name              = "/aws/lambda/${var.environment}-notifications-lambda"
  retention_in_days = 30 # the logs will be saved in CloudWatch for 30 days, after which they will be automatically deleted. 
  #Adjust this value based on your log retention requirements and compliance policies.
  tags = {
    Name        = "${var.environment}-notifications-lambda-log-group"
    Environment = var.environment
    Module      = "notifications"
  }
}
