name: Terraform CI/CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: eu-south-1
          role-session-name: github-actions-terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.4

      # Catch formatting syntax errors early
      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      # Validate code integration without calling AWS APIs
      - name: Terraform Validate
        run: terraform validate

      # Save plan file to ensure 'apply' executes exactly what was approved
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Apply only on push events to prevent unintended changes from PRs
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan

